Algoritmo "4numeros"

Var
n1, n2, n3, n4, soma: real

Inicio
escreval("Olá, vamos fazer uma coisa legal? ")
escreval("Digite um número: ")
leia(n1)
limpaTela()
escreval("Digite um segundo número: ")
leia(n2)
limpaTela()
escreval("Digite um terceiro número: ")
leia(n3)
limpaTela()
escreval("Digite um quarto número: ")
leia(n4)
limpaTela()

soma <- n1 + n2 + n3 + n4

escreval("----SURPRESA!!!-----")
escreval("A soma total de todos esses números é", soma)
Fimalgoritmo