Algoritmo "Atividade 1"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Victor Santos Rohod
// Descrição: Escreva um algoritmo para ler um valor e escrever seu antecessor
// Autor(a): Danielle Rodrigues Campos
// Data atual  : 23/10/2024
Var
numero, antecessor, resultado: inteiro

Inicio
escreva(" Olá, digite um número! ")
leia(numero)
limpaTela()

antecessor <- numero -1

escreva (" O antecessor de ", numero, " é : ", antecessor)

Fimalgoritmo