Algoritmo " Funcao"

Var

idade: inteiro

procedimento idadeNatação (idade : inteiro )
var
idade: inteiro
inicio

escreval(" Digite a sua idade: ")



fimProcedimento

Inicio
escreval("***IDADE NATAÇÃO******")
escreval ("Infantil A = 5 a 7 anos")
escreval ("Infantil B = 8 a 11 anos")
escreval ("Juvenil A = 12 a 13 anos")
escreval ("Juvenil B = 14 a 17 anos")
escreval ("Adultos = Maiores de 18 anos")


Fimalgoritmo