Algoritmo "WhileForUntil"

Var
contador , contador2 , contador3  : inteiro

Inicio
// while
enquanto (contador <= 10) faca
   escreval(contador)
   contador <- contador + 1
fimEnquanto

//for
escreval("-----------")
escreval(" PARA (for) ")
para contador2 <- 1 ate 10 passo 1 faca
   escreval(contador2)
fimPara

// until
escreval("----------")
escreval("REPITA (do until)")
repita
     escreval(contador3)
     contador3 <- contador3 + 1
ate (contador3 = 11)

Fimalgoritmo